
import React from 'react';

const faqData = [
  {
    question: 'What kind of apps can I build?',
    answer: 'You can build a wide variety of web and mobile applications, from social networks and e-commerce stores to productivity tools and internal dashboards. The complexity is only limited by the clarity of your prompt.'
  },
  {
    question: 'Do I own the code that is generated?',
    answer: 'Yes! You have full ownership of the generated code. You can download it, modify it, and host it wherever you like. There are no restrictions.'
  },
  {
    question: 'What technologies does it use?',
    answer: 'Our AI agents generate code using modern, popular frameworks like React, Next.js, Expo for mobile, Node.js for the backend, and Supabase for the database. We prioritize robust and scalable technologies.'
  },
  {
    question: 'How do I handle updates or changes?',
    answer: 'You can run the generator again with a modified prompt to iterate on your application. We are also building features to allow the AI to refactor and update existing codebases generated by the platform.'
  }
];

const FaqItem: React.FC<{ item: typeof faqData[0] }> = ({ item }) => (
  <details className="p-4 rounded-lg bg-glass-bg border border-glass-border backdrop-blur-md group">
    <summary className="font-semibold cursor-pointer list-none flex justify-between items-center">
      {item.question}
      <span className="transition-transform duration-300 group-open:rotate-45">+</span>
    </summary>
    <p className="mt-4 text-gray-400">{item.answer}</p>
  </details>
);

const FAQ: React.FC = () => {
  return (
    <section id="faq" className="py-20 md:py-32">
      <div className="w-full max-w-3xl mx-auto">
        <h2 className="text-3xl md:text-4xl font-orbitron font-bold text-center mb-12">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqData.map(item => (
            <FaqItem key={item.question} item={item} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default React.memo(FAQ);